name: monitoring
services:
  alloy:
    image: grafana/alloy:v1.5.1
    ports:
      - "12345:12345"
    volumes:
      - type: bind
        source: /volume1/docker/alloy/config.alloy
        target: /etc/alloy/config.alloy
      - type: bind
        source: /volume1/docker/alloy/snmp_auth.config.yml
        target: /etc/alloy/snmp_auth.config.yml
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=experimental",
      "/etc/alloy/config.alloy",
    ]