name: monitoring
services: 
  alloy:
    image: grafana/alloy:v1.5.1
    network_mode: bridge
    ports:
      - "12345:12345"
    volumes:
      - type: bind
        source: /volume1/docker/alloy/config.alloy
        target: /etc/alloy/config.alloy
      - type: bind
        source: /volume1/docker/alloy/snmp_auth.config.yml
        target: /etc/alloy/snmp_auth.config.yml
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=experimental",
      "/etc/alloy/config.alloy",
    ]
  p1:
    image: chriskies/homewizard-p1-prometheus:main
    network_mode: bridge
    ports:
      - "59898:9898"
    environment:
      HOST: 192.168.178.30
  watermeter:
    image: ghcr.io/loafoe/prometheus-watermeter-exporter:latest
    network_mode: bridge
    ports:
      - "59897:8880"
    entrypoint: ["/usr/bin/prometheus-watermeter-exporter"]
    command: [
      "--verbose",
      "--addr","http://192.168.178.73",
      "--listen", "0.0.0.0:8880"
    ]